### ISSUE TITLE
Activación por defecto de la opción "Variantes"

### ISSUE THREAD

**Issue by qupro** [zvERP/rental-vertical#10]
Al menos los módulos los Rental Base, Rental Off-Da, Rental Pricelist, Rental Product Pack piden la activación de las variantes "Ajustes > Alquiler > Productos" para su funcionamiento. Esta opción podría activarse por defecto.

En cualquier caso si no se activa , el menú productos no se despliega si no está activado.

**Comment by pcastelovigo** [comment]
[a6381f2](https://github.com/flinq-ingenieria/rental-vertical/commit/a6381f2c1de30fc9a8e5909485acd82e00dd7231) deberia solucionarlo, espero a probarlo para cerrar

gracias
